In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.metrics import accuracy_score,f1_score

In [2]:
df = pd.read_csv("F:\\Divya\\project 1\\Sleep_health_and_lifestyle_dataset.csv")

In [3]:
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB

In [5]:
df= df.dropna()

In [6]:
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia
6,7,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia
16,17,Female,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000,Sleep Apnea

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 155 entries, 3 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                155 non-null    int64
 1   Gender                   155 non-null    object
 2   Age                      155 non-null    int64
 3   Occupation               155 non-null    object
 4   Sleep Duration           155 non-null    float64
 5   Quality of Sleep         155 non-null    int64
 6   Physical Activity Level  155 non-null    int64
 7   Stress Level             155 non-null    int64
 8   BMI Category             155 non-null    object
 9   Blood Pressure           155 non-null    object
 10  Heart Rate               155 non-null    int64
 11  Daily Steps              155 non-null    int64
 12  Sleep Disorder           155 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 17.0+ KB

In [8]:
df[["Systolic","Diastolic"]] = df["Blood Pressure"].str.split("/",expand = True)

In [9]:
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Systolic,Diastolic
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,140,90
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,140,90
5,6,Male,28,Software Engineer,5.9,4,30,8,Obese,140/90,85,3000,Insomnia,140,90
6,7,Male,29,Teacher,6.3,6,40,7,Obese,140/90,82,3500,Insomnia,140,90
16,17,Female,29,Nurse,6.5,5,40,7,Normal Weight,132/87,80,4000,Sleep Apnea,132,87

In [10]:
df = df.drop(columns = ["Person ID","Blood Pressure"])

In [11]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Systolic,Diastolic
3,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90
4,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90
5,Male,28,Software Engineer,5.9,4,30,8,Obese,85,3000,Insomnia,140,90
6,Male,29,Teacher,6.3,6,40,7,Obese,82,3500,Insomnia,140,90
16,Female,29,Nurse,6.5,5,40,7,Normal Weight,80,4000,Sleep Apnea,132,87

In [12]:
cols = ["Gender","Occupation","BMI Category","Sleep Disorder"]
le = LabelEncoder()
for col in cols:
    df[col]=le.fit_transform(df[col])

In [13]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Systolic,Diastolic
3,1,28,5,5.9,4,30,8,2,85,3000,1,140,90
4,1,28,5,5.9,4,30,8,2,85,3000,1,140,90
5,1,28,8,5.9,4,30,8,2,85,3000,0,140,90
6,1,29,9,6.3,6,40,7,2,82,3500,0,140,90
16,0,29,4,6.5,5,40,7,1,80,4000,1,132,87

In [14]:
df["Systolic"] = pd.to_numeric(df["Systolic"])

In [15]:
df["Diastolic"] = pd.to_numeric(df["Diastolic"])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 155 entries, 3 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   155 non-null    int64
 1   Age                      155 non-null    int64
 2   Occupation               155 non-null    int64
 3   Sleep Duration           155 non-null    float64
 4   Quality of Sleep         155 non-null    int64
 5   Physical Activity Level  155 non-null    int64
 6   Stress Level             155 non-null    int64
 7   BMI Category             155 non-null    int64
 8   Heart Rate               155 non-null    int64
 9   Daily Steps              155 non-null    int64
 10  Sleep Disorder           155 non-null    int64
 11  Systolic                 155 non-null    int64
 12  Diastolic                155 non-null    int64
dtypes: float64(1), int64(12)
memory usage: 17.0 KB

In [17]:
df1 = df.copy()

In [18]:
X = df1.drop(columns = "Sleep Disorder")
y = df1["Sleep Disorder"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [20]:
base_learner = [
    ('LR',LogisticRegression()),
    ('DT',DecisionTreeClassifier()),
    ('KNN',KNeighborsClassifier())
]

meta_learner = SVC()
stacking_model = StackingClassifier(estimators=base_learner,final_estimator=meta_learner)

models = {
    "Logistic Regression" : LogisticRegression(),
    "KNN":KNeighborsClassifier(),
    "Decision Tree":DecisionTreeClassifier(),
    "Naive bayes":GaussianNB(),
    "SVM":SVC(),
    "RandomForestClassifier":RandomForestClassifier(n_estimators=50,random_state=42),
    "XGBoost":XGBClassifier(),
    "stacking":stacking_model
    
}

In [21]:
results = []

for name,model in models.items():
    model.fit(X_train_scaled,y_train)
    y_pred = model.predict(X_test_scaled)
    acc = accuracy_score(y_test,y_pred)
    f1 =f1_score(y_test,y_pred,average="macro")
    
    results.append({
        'model':name,
        'accuracy':round(acc,2),
        'f1':round(f1,2,)
    })

In [22]:
results

[{'model': 'Logistic Regression', 'accuracy': 0.85, 'f1': 0.84},
 {'model': 'KNN', 'accuracy': 0.92, 'f1': 0.92},
 {'model': 'Decision Tree', 'accuracy': 0.9, 'f1': 0.9},
 {'model': 'Naive bayes', 'accuracy': 0.81, 'f1': 0.81},
 {'model': 'SVM', 'accuracy': 0.85, 'f1': 0.84},
 {'model': 'RandomForestClassifier', 'accuracy': 0.87, 'f1': 0.86},
 {'model': 'XGBoost', 'accuracy': 0.87, 'f1': 0.86},
 {'model': 'stacking', 'accuracy': 0.85, 'f1': 0.84}]

In [23]:
KNN = KNeighborsClassifier()

In [24]:
import pickle

In [25]:
with open ("F:\\Divya\\project 1\\KNN.pkl","wb")as file:
    pickle.dump(KNN,file)

In [26]:
with open ("F:\\Divya\\project 1\\KNN.pkl","wb")as file:
    pickle.dump(scaler,file)

In [27]:
with open ("F:\\Divya\\project 1\\columns.pkl","wb")as file:
    pickle.dump(X.columns.tolist(),file)

In [28]:
cols = ["Gender","Occupation","BMI Category"]
encoders = {}
le = LabelEncoder()
for col in cols:
    X[col] = le.fit_transform(X[col])
    encoders[col] = le

In [29]:
with open ("F:\\Divya\\project 1\\label_encoders.pkl","wb") as file:
    pickle.dump(encoders,file)

In [30]:
import joblib

encoders = joblib.load("F:\\Divya\\project 1\\label_encoders.pkl")

for col, le in encoders.items():
    print(col, le.classes_)

Gender [0 1 2 3]
Occupation [0 1 2 3]
BMI Category [0 1 2 3]

In [31]:
from sklearn.preprocessing import LabelEncoder
import joblib
import pandas as pd

# Load your training dataset BEFORE encoding
df = pd.read_csv("F:\\Divya\\project 1\\Sleep_health_and_lifestyle_dataset.csv")
encoders = {}
for col in ['Gender', 'Occupation', 'BMI Category']:
    le = LabelEncoder()
    le.fit(df[col])   # <--- important: fit on text, not encoded numbers
    encoders[col] = le

with open ('F:\\Divya\\project 1\\label_encoders.pkl',"wb")as file:
    pickle .dump(encoders,file)


print("Encoders rebuilt and saved successfully!")

Encoders rebuilt and saved successfully!

In [32]:
encoders = joblib.load("F:\\Divya\\project 1\\label_encoders.pkl")

for col, le in encoders.items():
    print(col, le.classes_)

Gender ['Female' 'Male']
Occupation ['Accountant' 'Doctor' 'Engineer' 'Lawyer' 'Manager' 'Nurse'
 'Sales Representative' 'Salesperson' 'Scientist' 'Software Engineer'
 'Teacher']
BMI Category ['Normal' 'Normal Weight' 'Obese' 'Overweight']

In [33]:
joblib.load("F:\\Divya\\project 1\\KNN.pkl")
print(type(model))

<class 'sklearn.ensemble._stacking.StackingClassifier'>

In [34]:
Knn = KNeighborsClassifier(n_neighbors=5)
Knn.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [35]:
with open('F:\\Divya\\project 1\\Knn_model.pkl','wb')as file:
    pickle.dump(Knn,file)

In [36]:
print(y.value_counts())

Sleep Disorder
1    78
0    77
Name: count, dtype: int64

In [37]:
df["Sleep Disorder"].value_counts()

Sleep Disorder
Sleep Apnea    78
Insomnia       77
Name: count, dtype: int64

In [38]:
le = LabelEncoder()
y = le.fit_transform(df['Sleep Disorder'])
print(le.classes_)

['Insomnia' 'Sleep Apnea' nan]

In [39]:
y_pred = Knn.predict(X_test_scaled)
print(np.unique(y_pred,return_counts=True))

(array([0, 1]), array([33, 19]))

In [40]:

expected_columns = joblib.load("F:\\Divya\\project 1\\columns.pkl")

sample = pd.DataFrame([{
    "Age": 35,
    "Gender": "Female",
    "Occupation": "Teacher",
    "Sleep Duration": 6.5,
    "Quality of Sleep": 4,
    "Physical Activity Level": 50,
    "Stress Level": 8,
    "BMI Category": "Overweight",
    "Heart Rate": 85,
    "Daily Steps": 6000,
    "Systolic": 140,
    "Diastolic": 90
}])

for col in ["Gender", "Occupation", "BMI Category"]:
    sample[col] = encoders[col].transform(sample[col])

sample = sample[expected_columns]
scaled = scaler.transform(sample)
print(model.predict(scaled))

[1]